version: '2'
services:
  quectel-quecopen-dev:
    image: bacnh85/quectel-quecopen
    container_name: quectel-quecopen
    environment:
      - PUID=501
      - PGID=20
    volumes:
      - "nfsmount:/opt"
    tty: true
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"