version: '3.4'
services:
  quectel-quecopen-dev:
    image: bacnh85/quectel-quecopen
    container_name: quectel-quecopen
    environment:
      - PUID=501
      - PGID=20
    volumes:
      - "./:/opt"
    tty: true
