#!/bin/sh

# MacOS
install_packages_brew()
{ 
    # Install adnroid tool
    echo "Installing Andrroid Tools ... "
    brew cask install android-platform-tools

    # Setup NFS
    sh script/macos_setup_nfs.sh

    # Get UID, GID from the host and paste to docker container
    echo "Setting the UID, GID to the DockerFile"
    U=`id -u`
    G=`id -g`

    sed -i -e 's,UID=501,'UID="$U"',' Dockerfile
    sed -i -e 's,UNAME=bacnh,'UNAME="$USER"',' Dockerfile
}

install_packages_source()
{
    echo 'source not supported currently' && false
}

install_packages()
{
    PM=source
    if which brew; then
        PM=brew
    fi
    install_packages_$PM
}

main()
{
    install_packages
    
}

main
